Pro 2253 pr template
apostrophecms/.github pull request #5
Opened 2021-11-15 19:57 UTC by abea

2021-12-01 16:13 UTC, gregvanbrug requested changes

2021-12-01 16:13 UTC, gregvanbrug commented on .github/PULL_REQUEST_TEMPLATE.md
> +*Summarize the changes briefly, including which issue/ticket this resolves. If it closes an existing Github issue, include "Close #[issue number]"*
Should this be:
> ... "Closes #[issue number]"*

I think [either works](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) but "Closes" sounds more grammatically correct.

2021-12-01 16:13 UTC, gregvanbrug commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Refactor
Code style update and Refactor kinda feel the same. What is the difference between these two changes?

2021-12-01 16:13 UTC, gregvanbrug commented on .github/PULL_REQUEST_TEMPLATE.md
> +**If there is no related issue/ticket,** the PR's summary includes:
Should this be part of the next item so the list could be uninterrupted?
```
- [ ] **If there is no related issue/ticket,** the PR's summary includes a convincing reason for adding this feature or clear description of the bug it resolves
```

2021-12-01 16:13 UTC, gregvanbrug commented on .github/PULL_REQUEST_TEMPLATE.md
> +To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.
Should this read something more like:

```
If adding a new feature, it's best to open a **feature request issue** first and wait for approval before working on it.
```

Alright to leave as is but the way it is currently written has a bit of negative connotation to me.

2021-12-13 21:50 UTC, abea commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Refactor
No huge difference necessarily. I see "refactor" as possibly being more complex than code style, which might be a ton of spacing fixes and var=>const for eslint. I'll remove one to keep things simpler.

2021-12-17 14:41 UTC, gregvanbrug approved these changes

2021-12-20 20:29 UTC, merged